//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTechShop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BuyingAgent
    {
        public int Id { get; set; }
        [Required, MinLength(3), MaxLength(50), RegularExpression("[a-zA-Z][a-zA-Z ]+[a-zA-Z]$", ErrorMessage = "Please enter alphabetic characters for Full Name!")]
        public string FullName { get; set; }
        [Required, MinLength(3), MaxLength(30), RegularExpression("^[a-zA-Z0-9_]*$", ErrorMessage = "Please enter alphanumeric charcters for User Name!")]
        public string UserName { get; set; }
        public string ProfilePic { get; set; }
        [Required, MinLength(3), MaxLength(20)]
        public string Password { get; set; }
        [Required, EmailAddress, MinLength(10), MaxLength(50)]
        public string Email { get; set; }
        [Required, Phone, MinLength(11), MaxLength(11)]
        public string Phone { get; set; }
        [Required, MinLength(3), MaxLength(100)]
        public string Address { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
