//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Old_Products
    {
        public int Id { get; set; }
        public Nullable<int> CutomerId { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public string Status { get; set; }
        public decimal BuyingPrice { get; set; }
        public decimal SellingPrice { get; set; }
        public string Category { get; set; }
        public string Brand { get; set; }
        public string Features { get; set; }
        public int Quantity { get; set; }
        public string Images { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Tax { get; set; }
        public string Source { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
