//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineTechShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Log
    {
        public int Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public int Product_Id { get; set; }
        public Nullable<int> Sales_Executive_Id { get; set; }
        public System.DateTime Date_Sold { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Sale { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public decimal Total_Price { get; set; }
        public string Status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual SalesExecutive SalesExecutive { get; set; }
    }
}
